# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(631, 431)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(631, 431))
        mainWindow.setMaximumSize(QtCore.QSize(631, 431))
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 281, 251))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 330, 281, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.previousButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.previousButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/pre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon2)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.nextButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nextButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon3)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(460, 340, 151, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.muteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.muteButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/mute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.muteButton.setIcon(icon4)
        self.muteButton.setObjectName("muteButton")
        self.horizontalLayout_2.addWidget(self.muteButton)
        self.shuffleButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.shuffleButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/unshuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffleButton.setIcon(icon5)
        self.shuffleButton.setObjectName("shuffleButton")
        self.horizontalLayout_2.addWidget(self.shuffleButton)
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setGeometry(QtCore.QRect(329, 19, 271, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 269, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 271, 203))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.songNameLabel = QtWidgets.QLabel(self.centralWidget)
        self.songNameLabel.setGeometry(QtCore.QRect(20, 280, 281, 20))
        self.songNameLabel.setText("")
        self.songNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.songNameLabel.setObjectName("songNameLabel")
        self.directoryLabel = QtWidgets.QLabel(self.centralWidget)
        self.directoryLabel.setGeometry(QtCore.QRect(20, 0, 581, 16))
        self.directoryLabel.setObjectName("directoryLabel")
        self.volumeGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.volumeGroupBox.setGeometry(QtCore.QRect(320, 260, 120, 131))
        self.volumeGroupBox.setObjectName("volumeGroupBox")
        self.volumeProgressBar = QtWidgets.QProgressBar(self.volumeGroupBox)
        self.volumeProgressBar.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.volumeProgressBar.setProperty("value", 20)
        self.volumeProgressBar.setObjectName("volumeProgressBar")
        self.volumeDial = QtWidgets.QDial(self.volumeGroupBox)
        self.volumeDial.setGeometry(QtCore.QRect(10, 40, 91, 91))
        self.volumeDial.setMaximum(100)
        self.volumeDial.setObjectName("volumeDial")
        self.volumeLabel = QtWidgets.QLabel(self.volumeGroupBox)
        self.volumeLabel.setGeometry(QtCore.QRect(90, 30, 31, 20))
        self.volumeLabel.setObjectName("volumeLabel")
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 631, 22))
        self.menuBar.setObjectName("menuBar")
        self.File = QtWidgets.QMenu(self.menuBar)
        self.File.setObjectName("File")
        self.menuControls = QtWidgets.QMenu(self.menuBar)
        self.menuControls.setObjectName("menuControls")
        mainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtWidgets.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/note55.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFile.setIcon(icon6)
        self.actionFile.setObjectName("actionFile")
        self.actionPlay = QtWidgets.QAction(mainWindow)
        self.actionPlay.setIcon(icon)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtWidgets.QAction(mainWindow)
        self.actionStop.setIcon(icon1)
        self.actionStop.setObjectName("actionStop")
        self.actionPrevious = QtWidgets.QAction(mainWindow)
        self.actionPrevious.setIcon(icon2)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionNext = QtWidgets.QAction(mainWindow)
        self.actionNext.setIcon(icon3)
        self.actionNext.setObjectName("actionNext")
        self.actionMute = QtWidgets.QAction(mainWindow)
        self.actionMute.setIcon(icon4)
        self.actionMute.setObjectName("actionMute")
        self.actionShuffle = QtWidgets.QAction(mainWindow)
        self.actionShuffle.setIcon(icon5)
        self.actionShuffle.setObjectName("actionShuffle")
        self.actionSearch = QtWidgets.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch.setIcon(icon7)
        self.actionSearch.setObjectName("actionSearch")
        self.File.addAction(self.actionFile)
        self.File.addAction(self.actionSearch)
        self.menuControls.addAction(self.actionPlay)
        self.menuControls.addAction(self.actionStop)
        self.menuControls.addAction(self.actionPrevious)
        self.menuControls.addAction(self.actionNext)
        self.menuControls.addAction(self.actionMute)
        self.menuControls.addAction(self.actionShuffle)
        self.menuBar.addAction(self.File.menuAction())
        self.menuBar.addAction(self.menuControls.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MP3 Player"))
        self.label.setText(_translate("mainWindow", "TextLabel"))
        self.label_2.setText(_translate("mainWindow", "TextLabel"))
        self.label_3.setText(_translate("mainWindow", "TextLabel"))
        self.label_4.setText(_translate("mainWindow", "TextLabel"))
        self.label_5.setText(_translate("mainWindow", "TextLabel"))
        self.label_6.setText(_translate("mainWindow", "TextLabel"))
        self.directoryLabel.setText(_translate("mainWindow", "Directory label"))
        self.volumeGroupBox.setTitle(_translate("mainWindow", "Volume"))
        self.volumeLabel.setText(_translate("mainWindow", "20"))
        self.File.setTitle(_translate("mainWindow", "File"))
        self.menuControls.setTitle(_translate("mainWindow", "Controls"))
        self.actionFile.setText(_translate("mainWindow", "Open..."))
        self.actionPlay.setText(_translate("mainWindow", "Play"))
        self.actionStop.setText(_translate("mainWindow", "Stop"))
        self.actionPrevious.setText(_translate("mainWindow", "Previous"))
        self.actionNext.setText(_translate("mainWindow", "Next"))
        self.actionMute.setText(_translate("mainWindow", "Mute"))
        self.actionShuffle.setText(_translate("mainWindow", "Shuffle"))
        self.actionSearch.setText(_translate("mainWindow", "Search"))


