# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 420)
        MainWindow.setMaximumSize(QtCore.QSize(400, 420))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(220, 10, 171, 241))
        self.listWidget.setObjectName("listWidget")
        self.vSlider = QtWidgets.QSlider(self.centralWidget)
        self.vSlider.setGeometry(QtCore.QRect(10, 290, 231, 22))
        self.vSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vSlider.setObjectName("vSlider")
        self.time = QtWidgets.QLabel(self.centralWidget)
        self.time.setGeometry(QtCore.QRect(250, 290, 47, 13))
        self.time.setObjectName("time")
        self.art = QtWidgets.QLabel(self.centralWidget)
        self.art.setGeometry(QtCore.QRect(10, 30, 201, 191))
        self.art.setText("")
        self.art.setObjectName("art")
        self.infoLabel = QtWidgets.QLabel(self.centralWidget)
        self.infoLabel.setGeometry(QtCore.QRect(20, 230, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.infoLabel.setFont(font)
        self.infoLabel.setText("")
        self.infoLabel.setTextFormat(QtCore.Qt.RichText)
        self.infoLabel.setWordWrap(False)
        self.infoLabel.setObjectName("infoLabel")
        self.dial = QtWidgets.QDial(self.centralWidget)
        self.dial.setGeometry(QtCore.QRect(270, 250, 121, 111))
        self.dial.setProperty("value", 50)
        self.dial.setObjectName("dial")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setGeometry(QtCore.QRect(280, 360, 121, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.status = QtWidgets.QLabel(self.centralWidget)
        self.status.setGeometry(QtCore.QRect(280, 376, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 330, 242, 66))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.playbutton.setMinimumSize(QtCore.QSize(64, 64))
        self.playbutton.setBaseSize(QtCore.QSize(64, 64))
        self.playbutton.setStyleSheet("")
        self.playbutton.setText("")
        self.playbutton.setIconSize(QtCore.QSize(64, 64))
        self.playbutton.setObjectName("playbutton")
        self.horizontalLayout.addWidget(self.playbutton)
        self.stopbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.stopbutton.setMinimumSize(QtCore.QSize(32, 32))
        self.stopbutton.setMaximumSize(QtCore.QSize(32, 32))
        self.stopbutton.setBaseSize(QtCore.QSize(32, 32))
        self.stopbutton.setText("")
        self.stopbutton.setIconSize(QtCore.QSize(32, 32))
        self.stopbutton.setObjectName("stopbutton")
        self.horizontalLayout.addWidget(self.stopbutton)
        self.nextbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.nextbutton.setMinimumSize(QtCore.QSize(32, 32))
        self.nextbutton.setMaximumSize(QtCore.QSize(32, 32))
        self.nextbutton.setBaseSize(QtCore.QSize(32, 32))
        self.nextbutton.setText("")
        self.nextbutton.setIconSize(QtCore.QSize(32, 32))
        self.nextbutton.setObjectName("nextbutton")
        self.horizontalLayout.addWidget(self.nextbutton)
        self.prebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.prebutton.setMinimumSize(QtCore.QSize(32, 32))
        self.prebutton.setMaximumSize(QtCore.QSize(32, 32))
        self.prebutton.setBaseSize(QtCore.QSize(32, 32))
        self.prebutton.setText("")
        self.prebutton.setIconSize(QtCore.QSize(32, 32))
        self.prebutton.setObjectName("prebutton")
        self.horizontalLayout.addWidget(self.prebutton)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 250, 62, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.shuffle = QtWidgets.QPushButton(self.layoutWidget1)
        self.shuffle.setMinimumSize(QtCore.QSize(24, 24))
        self.shuffle.setMaximumSize(QtCore.QSize(16, 16))
        self.shuffle.setText("")
        self.shuffle.setIconSize(QtCore.QSize(24, 24))
        self.shuffle.setObjectName("shuffle")
        self.horizontalLayout_2.addWidget(self.shuffle)
        self.mute = QtWidgets.QPushButton(self.layoutWidget1)
        self.mute.setMinimumSize(QtCore.QSize(30, 24))
        self.mute.setMaximumSize(QtCore.QSize(16, 16))
        self.mute.setText("")
        self.mute.setIconSize(QtCore.QSize(30, 24))
        self.mute.setObjectName("mute")
        self.horizontalLayout_2.addWidget(self.mute)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.listWidget.raise_()
        self.vSlider.raise_()
        self.time.raise_()
        self.art.raise_()
        self.infoLabel.raise_()
        self.dial.raise_()
        self.progressBar.raise_()
        self.status.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuControls = QtWidgets.QMenu(self.menuBar)
        self.menuControls.setObjectName("menuControls")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon2)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon3)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon4)
        self.actionStop.setObjectName("actionStop")
        self.actionNext = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon5)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/pre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious.setIcon(icon6)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionActionAboutUs = QtWidgets.QAction(MainWindow)
        self.actionActionAboutUs.setObjectName("actionActionAboutUs")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionShuffle = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/unshuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShuffle.setIcon(icon7)
        self.actionShuffle.setObjectName("actionShuffle")
        self.actionMute = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/mute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMute.setIcon(icon8)
        self.actionMute.setObjectName("actionMute")
        self.menuFile.addAction(self.actionOpen)
        self.menuControls.addAction(self.actionPlay)
        self.menuControls.addAction(self.actionPause)
        self.menuControls.addAction(self.actionStop)
        self.menuControls.addAction(self.actionNext)
        self.menuControls.addAction(self.actionPrevious)
        self.menuControls.addAction(self.actionShuffle)
        self.menuControls.addAction(self.actionMute)
        self.menuAbout.addAction(self.actionActionAboutUs)
        self.menuAbout.addAction(self.actionAboutQt)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuControls.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.listWidget.setCurrentRow(-1)
        self.dial.valueChanged['int'].connect(self.progressBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mp3Factory"))
        self.listWidget.setSortingEnabled(True)
        self.time.setText(_translate("MainWindow", "00:00"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuControls.setTitle(_translate("MainWindow", "Controls"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open file"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionPlay.setText(_translate("MainWindow", "play"))
        self.actionPlay.setShortcut(_translate("MainWindow", "Space"))
        self.actionPause.setText(_translate("MainWindow", "pause"))
        self.actionStop.setText(_translate("MainWindow", "stop"))
        self.actionStop.setShortcut(_translate("MainWindow", "Esc"))
        self.actionNext.setText(_translate("MainWindow", "next"))
        self.actionNext.setToolTip(_translate("MainWindow", "Next Song"))
        self.actionNext.setShortcut(_translate("MainWindow", "PgUp"))
        self.actionPrevious.setText(_translate("MainWindow", "previous"))
        self.actionPrevious.setToolTip(_translate("MainWindow", "Previous Song"))
        self.actionPrevious.setShortcut(_translate("MainWindow", "PgDown"))
        self.actionActionAboutUs.setText(_translate("MainWindow", "actionAboutUs"))
        self.actionActionAboutUs.setShortcut(_translate("MainWindow", "F11"))
        self.actionAboutQt.setText(_translate("MainWindow", "aboutQt"))
        self.actionAboutQt.setShortcut(_translate("MainWindow", "F12"))
        self.actionShuffle.setText(_translate("MainWindow", "shuffle"))
        self.actionShuffle.setToolTip(_translate("MainWindow", "Shuffle songs"))
        self.actionShuffle.setShortcut(_translate("MainWindow", "Ctrl+Tab"))
        self.actionMute.setText(_translate("MainWindow", "mute"))
        self.actionMute.setToolTip(_translate("MainWindow", "Mute"))
        self.actionMute.setShortcut(_translate("MainWindow", "M"))


import icon_rc
